spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: event-participation-service


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true




