import {faHeart as faHeartRegular, IconDefinition} from "@fortawesome/free-regular-svg-icons";
import {
  faBackwardStep,
  faBook,
  faChevronLeft,
  faChevronRight,
  faCircleNotch,
  faCirclePause,
  faCirclePlay,
  faCircleXmark,
  faCompactDisc,
  faForwardStep,
  faHeart,
  faHome,
  faMicrophoneAlt,
  faMusic,
  faPlus,
  faSearch,
  faTrash,
  faUser,
  faUsers,
  faVolumeHigh,
  faVolumeLow,
  faVolumeMute,
  faCalendar,
  faTrashCan,
  faGuitar,
  faStar,
  faFire,
  faHeadphones,
  faBroadcastTower,
  faSun,
  faHatCowboy,
  faRepeat,
  faRandom,
  faDrum,
  faSkull,
  faLeaf,
  faRecordVinyl,
  faPlay,
  faCheckCircle,
  faExclamationCircle,
  faShuffle,
  faExpand,
  faListUl,
  faThLarge, faList, faUpload, faMinus, faCalendarTimes, faClock, faMapMarkerAlt, faInfoCircle, faCalendarAlt,
} from "@fortawesome/free-solid-svg-icons";
import {faSpotify, faYoutube} from "@fortawesome/free-brands-svg-icons";

export const fontAwesomeIcons: IconDefinition[] = [
  faCirclePlay,
  faHome,
  faSearch,
  faBook,
  faPlus,
  faChevronLeft,
  faChevronRight,
  faUser,
  faCircleNotch,
  faCircleXmark,
  faBackwardStep,
  faForwardStep,
  faCirclePause,
  faVolumeMute,
  faVolumeLow,
  faVolumeHigh,
  faHeart,
  faHeartRegular,
  faMusic,
  faCompactDisc,
  faMicrophoneAlt,
  faUsers,
  faTrash,
  faCalendar,
  faTrashCan,
  faGuitar,
  faCompactDisc,
  faStar,
  faFire,
  faHeadphones,
  faBroadcastTower,
  faSun,
  faHatCowboy,
  faDrum,
  faSkull,
  faLeaf,
  faRecordVinyl,
  faPlay,
  faExclamationCircle,
  faCheckCircle,
  faRepeat,
  faRandom,
  faShuffle,
  faListUl,
  faExpand,
  faThLarge,
  faList,
  faSpotify,
  faUpload,
  faMinus,
  faYoutube,
  faCalendarTimes,
  faClock,
  faMapMarkerAlt,
  faInfoCircle,
  faCalendarAlt,












]
