services:
  postgresql:
    container_name: ms_spotify_sql
    image: postgres
    environment:
      POSTGRES_USER: omar
      POSTGRES_PASSWORD: omar
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  keycloak:
    container_name: keycloak-ms-spotify
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9098:8080
    volumes:
      - ./keycloak-realm-config:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - microservices-net
    command:
      - "start-dev"
      - "--import-realm"

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: