spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/SpotifyClone"
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-server

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: API Gateway
        url: /v3/api-docs
      - name: Music Service
        url: /aggregate/music-service/v3/api-docs
      - name: Artist Service
        url: /aggregate/artist-service/v3/api-docs
      - name: User Service
        url: /aggregate/user-service/v3/api-docs
      - name: Favourite Service
        url: /aggregate/favorites-service/v3/api-docs
      - name: Follow Service
        url: /aggregate/follow-service/v3/api-docs
      - name: Playlist Service
        url: /aggregate/playlist-service/v3/api-docs
      - name: Event Service
        url: /aggregate/event-service/v3/api-docs

music-service.url: http://localhost:8060
artist-service.url: http://localhost:8050
user-service.url: http://localhost:8090
favorites-service.url: http://localhost:8040
follow-service.url: http://localhost:8030
playlist-service.url: http://localhost:8020
event-service.url: http://localhost:8010
