eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**

        - id: artist-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/artists/**

        - id: music-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/songs/**

        - id: favorites-service
          uri: http://localhost:8040
          predicates:
            - Path=/api/v1/favourites/**

        - id: follow-service
          uri: http://localhost:8030
          predicates:
            - Path=/api/v1/follows/**

        - id: playlist-service
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/playlists/**

        - id: event-service
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/events/**

        - id: assets
          uri: http://localhost:8010  # event-service
          predicates:
            - Path=/assets/**



