eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**

        - id: artist-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/artists/**

        - id: music-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/songs/**

